import type Network from '../network';

/**
 * WebGPU shader-stage bit for compute visibility.
 *
 * Mirrored locally because the jsdom test environment does not expose
 * `GPUShaderStage` at runtime.
 */
const GPU_SHADER_STAGE_COMPUTE = 0x0004;

/**
 * First-kernel activation subset, indexed into the worker registry in
 * `src/multithreading/multi.utils.ts` `ACTIVATION_FUNCTIONS`.
 *
 * The WGSL switch generated by {@link createActivationKernel} must declare a
 * case for every index in this list so the GPU path can dispatch the same
 * activation functions as the CPU worker serialization contract.
 */
export const SUPPORTED_ACTIVATION_INDICES = [
  0, 1, 2, 3, 4, 5, 9, 10, 11, 12, 13,
] as const;

/**
 * Read the activation index that the network would use from its first
 * computation node.
 *
 * The fast-slab CPU path assigns a stable activation-function index to every
 * node's `squash` function. The GPU kernel mirrors that index in a WGSL switch.
 *
 * @param network - Network whose first node's activation index will drive the
 *   kernel switch.
 * @returns The activation index stored on the first node's squash function.
 * @throws Error when the network has no nodes or the first node has no indexed
 *   squash function.
 */
function readActivationIndex(network: Network): number {
  const node = network.nodes.at(0);
  const squash = node?.squash as
    | (((x: number, derivate?: boolean) => number) & { index?: number })
    | undefined;

  if (
    node === undefined ||
    typeof squash !== 'function' ||
    typeof squash.index !== 'number'
  ) {
    throw new Error(
      'Network topology is not eligible for GPU activation kernel',
    );
  }

  return squash.index;
}

/**
 * Build the WGSL source for a placeholder forward-pass activation kernel.
 *
 * This is intentionally a red-test seam, not a real GPU implementation. It
 * produces a syntactically valid WGSL module that exposes the expected compute
 * entry point, storage bindings, and activation switch so that compile-contract
 * tests can verify the kernel surface before Phase 4 fills in the actual
 * topology traversal.
 *
 * @param activationIndex - Activation index that must appear as a switch case.
 * @returns WGSL source string.
 */
function generateActivationSource(activationIndex: number): string {
  const supportedCases = SUPPORTED_ACTIVATION_INDICES.map(
    (index) => `    case ${index}: { return activation_${index}(x); }`,
  ).join('\n');

  const activationStubs = SUPPORTED_ACTIVATION_INDICES.map(
    (index) => `fn activation_${index}(x: f32) -> f32 { return x; }`,
  ).join('\n');

  return `@group(0) @binding(0) var<storage, read> weights: array<f32>;
@group(0) @binding(1) var<storage, read> from_nodes: array<u32>;
@group(0) @binding(2) var<storage, read> to_nodes: array<u32>;
@group(0) @binding(3) var<storage, read> flags: array<u32>;
@group(0) @binding(4) var<storage, read> outStart: array<u32>;
@group(0) @binding(5) var<storage, read> outOrder: array<u32>;
@group(0) @binding(6) var<storage, read_write> outputs: array<f32>;

// Placeholder activation stubs for the first supported subset.
${activationStubs}

fn applyActivation(index: u32, x: f32) -> f32 {
  switch(index) {
${supportedCases}
    default: { return x; }
  }
}

@compute @workgroup_size(64)
fn forward() {
  // Placeholder compute entry point for the red-test seam.
  // Selected activation index ${activationIndex} is covered by the switch above.
}
`;
}

/**
 * Generate a placeholder WGSL activation kernel for a supported network.
 *
 * The returned source is not intended to be run on real hardware yet; it
 * satisfies the compile-contract tests in Phase 3 by exposing the correct
 * entry point name, workgroup size, storage bindings, and activation switch.
 *
 * @param network - Network whose activation index and topology are inspected.
 * @returns Non-empty WGSL source string.
 * @throws Error when the activation index is unsupported or the network
 *   topology is ineligible.
 *
 * @example
 * ```ts
 * const source = createActivationKernel(network);
 * const module = device.createShaderModule({ code: source });
 * ```
 */
export function createActivationKernel(network: Network): string {
  const activationIndex = readActivationIndex(network);

  if (
    !(SUPPORTED_ACTIVATION_INDICES as readonly number[]).includes(
      activationIndex,
    )
  ) {
    throw new Error(`activation index ${activationIndex} is not supported`);
  }

  return generateActivationSource(activationIndex);
}

/**
 * Create the bind-group layout used by the GPU forward-pass kernel.
 *
 * The layout exposes seven storage-buffer entries in the exact order expected
 * by the slab-to-GPU upload contract: connection weights, source node ids,
 * target node ids, connection flags, CSR output-start offsets, CSR output
 * order, and the per-node output buffer.
 *
 * @param device - WebGPU device used to create the layout.
 * @returns A bind-group layout with seven storage-buffer entries.
 *
 * @example
 * ```ts
 * const bindGroupLayout = createBindGroupLayout(device);
 * ```
 */
export function createBindGroupLayout(device: GPUDevice): GPUBindGroupLayout {
  return device.createBindGroupLayout({
    entries: [
      {
        binding: 0,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 1,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 2,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 3,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 4,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 5,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 6,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'storage' },
      },
    ],
  });
}

/**
 * Build a compute pipeline from a shader module and a bind-group layout.
 *
 * The pipeline uses the `forward` compute entry point and a pipeline layout
 * built from the supplied bind-group layout. This placeholder mirrors the
 * contract the real GPU inference path will use in Phase 4.
 *
 * @param device - WebGPU device used to create the pipeline layout and pipeline.
 * @param shaderModule - Shader module containing the `forward` entry point.
 * @param bindGroupLayout - Layout describing the kernel's storage buffers.
 * @returns A compute pipeline configured for the forward-pass kernel.
 * @throws Error when pipeline creation fails.
 *
 * @example
 * ```ts
 * const pipeline = buildGPUPipeline(device, shaderModule, bindGroupLayout);
 * ```
 */
export function buildGPUPipeline(
  device: GPUDevice,
  shaderModule: GPUShaderModule,
  bindGroupLayout: GPUBindGroupLayout,
): GPUComputePipeline {
  const pipelineLayout = device.createPipelineLayout({
    bindGroupLayouts: [bindGroupLayout],
  });

  return device.createComputePipeline({
    layout: pipelineLayout,
    compute: {
      module: shaderModule,
      entryPoint: 'forward',
    },
  });
}
