import type Network from '../network';
import {
  buildActivationRegistry,
  formatActivationFunctionsWgsl,
  SUPPORTED_ACTIVATION_INDICES,
} from './network.gpu.activation.wgsl';

/**
 * WebGPU shader-stage bit for compute visibility.
 *
 * Mirrored locally because the jsdom test environment does not expose
 * `GPUShaderStage` at runtime.
 */
const GPU_SHADER_STAGE_COMPUTE = 0x0004;

/**
 * First-kernel activation subset, indexed into the worker registry in
 * `src/multithreading/multi.utils.ts` `ACTIVATION_FUNCTIONS`.
 *
 * The WGSL switch generated by {@link createActivationKernel} must declare a
 * case for every index in this list so the GPU path can dispatch the same
 * activation functions as the CPU worker serialization contract.
 */
export { SUPPORTED_ACTIVATION_INDICES };

/**
 * Read the activation index that the network would use from its first
 * computation node.
 *
 * The fast-slab CPU path assigns a stable activation-function index to every
 * node's `squash` function. The GPU kernel mirrors that index in a WGSL switch.
 *
 * @param network - Network whose first node's activation index will drive the
 *   kernel switch.
 * @returns The activation index stored on the first node's squash function.
 * @throws Error when the network has no nodes or the first node has no indexed
 *   squash function.
 */
function readActivationIndex(network: Network): number {
  const node = network.nodes.at(0);
  const squash = node?.squash as
    | (((x: number, derivate?: boolean) => number) & { index?: number })
    | undefined;

  if (
    node === undefined ||
    typeof squash !== 'function' ||
    typeof squash.index !== 'number'
  ) {
    throw new Error(
      'Network topology is not eligible for GPU activation kernel',
    );
  }

  return squash.index;
}

/**
 * Size of the one-dimensional compute workgroup used by the activation kernel.
 */
const WORKGROUP_SIZE = 64;

/**
 * Build the WGSL source for the forward-pass activation kernel.
 *
 * The shader exposes the seven storage-buffer bindings from the slab upload
 * contract, declares a real f32 activation function for every supported worker
 * index, and dispatches one thread per node in topological order. The current
 * kernel applies the network's canonical activation index to the per-node output
 * buffer; full weighted fan-out is intentionally left for the parity slice that
 * owns the complete forward pass.
 *
 * @param activationIndex - Activation index that must appear as a switch case.
 * @param nodeCount - Number of nodes in the network; bounds the dispatch.
 * @returns WGSL source string.
 */
function generateActivationSource(
  activationIndex: number,
  nodeCount: number,
): string {
  const registry = buildActivationRegistry();
  const activationFunctions = formatActivationFunctionsWgsl(registry);
  const supportedCases = registry
    .map(
      (entry) =>
        `    case ${entry.index}: { activationValue = activation_${entry.index}(activationValue); }`,
    )
    .join('\n');

  return `const NODE_COUNT: u32 = ${nodeCount}u;
const WORKGROUP_SIZE: u32 = ${WORKGROUP_SIZE}u;
const ACTIVATION_INDEX: i32 = ${activationIndex}i;

@group(0) @binding(0) var<storage, read> weights: array<f32>;
@group(0) @binding(1) var<storage, read> from_nodes: array<u32>;
@group(0) @binding(2) var<storage, read> to_nodes: array<u32>;
@group(0) @binding(3) var<storage, read> connection_flags: array<u32>;
@group(0) @binding(4) var<storage, read> out_start: array<u32>;
@group(0) @binding(5) var<storage, read> out_order: array<u32>;
@group(0) @binding(6) var<storage, read_write> node_outputs: array<f32>;

${activationFunctions}

@compute @workgroup_size(${WORKGROUP_SIZE})
fn forward() {
  let nodeIndex = global_invocation_id.x;
  if (nodeIndex >= NODE_COUNT) {
    return;
  }

  var activationValue = node_outputs[nodeIndex];
  switch (ACTIVATION_INDEX) {
${supportedCases}
    default: { break; }
  }
  node_outputs[nodeIndex] = activationValue;
}
`;
}

/**
 * Generate the WGSL source for the activation kernel of a supported network.
 *
 * The returned source is a real, bindable compute shader: it declares the
 * seven storage-buffer bindings, one f32 activation function per supported
 * worker index, and a `forward` entry point that dispatches one thread per
 * node. Unsupported activations or ineligible topologies are rejected before
 * any source is emitted.
 *
 * @param network - Network whose activation index and topology are inspected.
 * @returns Non-empty WGSL source string.
 * @throws Error when the activation index is unsupported or the network
 *   topology is ineligible.
 *
 * @example
 * ```ts
 * const source = createActivationKernel(network);
 * const module = device.createShaderModule({ code: source });
 * ```
 */
export function createActivationKernel(network: Network): string {
  const activationIndex = readActivationIndex(network);

  if (
    !(SUPPORTED_ACTIVATION_INDICES as readonly number[]).includes(
      activationIndex,
    )
  ) {
    throw new Error(`activation index ${activationIndex} is not supported`);
  }

  return generateActivationSource(activationIndex, network.nodes.length);
}

/**
 * Internal slab-backed shape used only to read CSR source/target arrays for
 * topology hashing. Optional because compile-contract tests use shallow network
 * stubs that do not carry slab state.
 */
interface InternalSlabNetwork extends Network {
  /** Source node index per connection, when the slab has been materialized. */
  _connFrom?: Uint32Array;
  /** Target node index per connection, when the slab has been materialized. */
  _connTo?: Uint32Array;
}

/** Pipeline cache keyed by topology hash, scoped per device. */
const pipelineCache = new WeakMap<GPUDevice, Map<string, GPUComputePipeline>>();

/**
 * Return the per-device pipeline cache map, creating it on first use.
 */
function getDevicePipelineCache(
  device: GPUDevice,
): Map<string, GPUComputePipeline> {
  let cache = pipelineCache.get(device);
  if (!cache) {
    cache = new Map();
    pipelineCache.set(device, cache);
  }
  return cache;
}

/** Mix one integer into a simple 32-bit rolling hash. */
function mixHash(hash: number, value: number): number {
  return ((hash << 5) - hash + value) | 0;
}

/**
 * Compute a deterministic key that identifies the network topology.
 *
 * The key includes node and connection counts plus the CSR from/to arrays when
 * they are available. Networks that differ only in weights therefore share a
 * key, which is exactly the condition that lets the pipeline cache reuse the
 * same compiled shader.
 *
 * @param network - Network whose topology will be hashed.
 * @param activationIndex - Activation index that changes the generated shader.
 * @returns A stable string key for the pipeline cache.
 */
function computeTopologyKey(network: Network, activationIndex: number): string {
  const nodeCount = network.nodes.length;
  const connectionCount = network.connections.length;
  const slabNetwork = network as InternalSlabNetwork;

  if (slabNetwork._connFrom && slabNetwork._connTo) {
    const from = slabNetwork._connFrom;
    const to = slabNetwork._connTo;
    let hash = 0;
    for (let index = 0; index < from.length; index++) {
      hash = mixHash(hash, from[index]);
    }
    for (let index = 0; index < to.length; index++) {
      hash = mixHash(hash, to[index]);
    }
    return `${activationIndex}:${nodeCount}:${connectionCount}:${hash}`;
  }

  return `${activationIndex}:${nodeCount}:${connectionCount}`;
}

/**
 * Compile (or reuse) the activation compute pipeline for a network topology.
 *
 * The pipeline is created once per unique topology and cached on the supplied
 * device. Recompilations with identical topology but different weights reuse
 * the cached `GPUComputePipeline`, satisfying the compile-stall mitigation in the
 * WebGPU skill. The shader module, bind-group layout, and pipeline creation
 * calls remain observable through the mock device used by owner-local tests.
 *
 * @param device - WebGPU device used to compile the compute pipeline.
 * @param network - Network whose topology and activation index drive the kernel.
 * @returns A compute pipeline configured for the `forward` entry point.
 * @throws Error when the network has no nodes, lacks an activation index, or
 *   requests an unsupported activation.
 *
 * @example
 * ```ts
 * const pipeline = compileActivationKernel(device, network);
 * ```
 */
export function compileActivationKernel(
  device: GPUDevice,
  network: Network,
): GPUComputePipeline {
  const activationIndex = readActivationIndex(network);

  if (
    !(SUPPORTED_ACTIVATION_INDICES as readonly number[]).includes(
      activationIndex,
    )
  ) {
    throw new Error(`activation index ${activationIndex} is not supported`);
  }

  const topologyKey = computeTopologyKey(network, activationIndex);
  const cache = getDevicePipelineCache(device);
  const cached = cache.get(topologyKey);
  if (cached) {
    return cached;
  }

  const source = generateActivationSource(
    activationIndex,
    network.nodes.length,
  );
  const shaderModule = device.createShaderModule({ code: source });
  const bindGroupLayout = createBindGroupLayout(device);
  const pipeline = buildGPUPipeline(device, shaderModule, bindGroupLayout);
  cache.set(topologyKey, pipeline);
  return pipeline;
}

/**
 * Create the bind-group layout used by the GPU forward-pass kernel.
 *
 * The layout exposes seven storage-buffer entries in the exact order expected
 * by the slab-to-GPU upload contract: connection weights, source node ids,
 * target node ids, connection flags, CSR output-start offsets, CSR output
 * order, and the per-node output buffer.
 *
 * @param device - WebGPU device used to create the layout.
 * @returns A bind-group layout with seven storage-buffer entries.
 *
 * @example
 * ```ts
 * const bindGroupLayout = createBindGroupLayout(device);
 * ```
 */
export function createBindGroupLayout(device: GPUDevice): GPUBindGroupLayout {
  return device.createBindGroupLayout({
    entries: [
      {
        binding: 0,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 1,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 2,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 3,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 4,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 5,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 6,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'storage' },
      },
    ],
  });
}

/**
 * Build a compute pipeline from a shader module and a bind-group layout.
 *
 * The pipeline uses the `forward` compute entry point and a pipeline layout
 * built from the supplied bind-group layout. It is the factory used by
 * {@link compileActivationKernel} to materialize the compiled GPU path.
 *
 * @param device - WebGPU device used to create the pipeline layout and pipeline.
 * @param shaderModule - Shader module containing the `forward` entry point.
 * @param bindGroupLayout - Layout describing the kernel's storage buffers.
 * @returns A compute pipeline configured for the forward-pass kernel.
 * @throws Error when pipeline creation fails.
 *
 * @example
 * ```ts
 * const pipeline = buildGPUPipeline(device, shaderModule, bindGroupLayout);
 * ```
 */
export function buildGPUPipeline(
  device: GPUDevice,
  shaderModule: GPUShaderModule,
  bindGroupLayout: GPUBindGroupLayout,
): GPUComputePipeline {
  const pipelineLayout = device.createPipelineLayout({
    bindGroupLayouts: [bindGroupLayout],
  });

  return device.createComputePipeline({
    layout: pipelineLayout,
    compute: {
      module: shaderModule,
      entryPoint: 'forward',
    },
  });
}
