import type Network from '../network';
import {
  buildActivationRegistry,
  formatActivationFunctionsWgsl,
  SUPPORTED_ACTIVATION_INDICES,
} from './network.gpu.activation.wgsl';

/**
 * WebGPU shader-stage bit for compute visibility.
 *
 * Mirrored locally because the jsdom test environment does not expose
 * `GPUShaderStage` at runtime.
 */
const GPU_SHADER_STAGE_COMPUTE = 0x0004;

/**
 * First-kernel activation subset, indexed into the worker registry in
 * `src/multithreading/multi.utils.ts` `ACTIVATION_FUNCTIONS`.
 *
 * The WGSL switch generated by `createActivationKernel` must declare a
 * case for every index in this list so the GPU path can dispatch the same
 * activation functions as the CPU worker serialization contract.
 */
export { SUPPORTED_ACTIVATION_INDICES };

/**
 * Read the activation index that the network would use from its first
 * computation node.
 *
 * The fast-slab CPU path assigns a stable activation-function index to every
 * node's `squash` function. The GPU kernel mirrors that index in a WGSL switch.
 *
 * @param network - Network whose first node's activation index will drive the
 *   kernel switch.
 * @returns The activation index stored on the first node's squash function.
 * @throws Error when the network has no nodes or the first node has no indexed
 *   squash function.
 */
function readActivationIndex(network: Network): number {
  const node = network.nodes.at(0);
  const squash = node?.squash as
    | (((x: number, derivate?: boolean) => number) & { index?: number })
    | undefined;

  if (
    node === undefined ||
    typeof squash !== 'function' ||
    typeof squash.index !== 'number'
  ) {
    throw new Error(
      'Network topology is not eligible for GPU activation kernel',
    );
  }

  return squash.index;
}

/**
 * Size of the one-dimensional compute workgroup used by the activation kernel.
 */
const WORKGROUP_SIZE = 64;

/**
 * Build the WGSL source for the struct-packed forward-pass activation kernel.
 *
 * The shader exposes six bindings: a read-only connection struct array, a
 * read-write node struct array, a read-write output array, a per-dispatch
 * params uniform, a read-only per-node topological level array, and a
 * read-only incoming-CSR start-offset array. One thread is dispatched per node
 * and threads that do not belong to the current level early-exit.
 *
 * @param network - Network whose activation index, topology, and slab arrays
 *   drive the generated shader.
 * @returns WGSL source string.
 * @throws Error when the network has no nodes or lacks an indexed squash
 *   function.
 */
function generateActivationSource(network: Network): string {
  const registry = buildActivationRegistry();
  const activationFunctions = formatActivationFunctionsWgsl(registry);
  const supportedCases = registry
    .map(
      (entry) =>
        `    case ${entry.index}: { return activation_${entry.index}(x); }`,
    )
    .join('\n');

  const activationIndex = readActivationIndex(network);

  return `const WORKGROUP_SIZE: u32 = ${WORKGROUP_SIZE}u;
const ACTIVATION_INDEX: i32 = ${activationIndex}i;

struct Connection {
  from_node: u32,
  to_node: u32,
  weight: f32,
  flags: u32,
};

struct Node {
  activation_state: f32,
  derivative_state: f32,
  error: f32,
  flags: u32,
};

struct Params {
  level: u32,
  node_count: u32,
  connection_count: u32,
  output_start: u32,
};

@group(0) @binding(0) var<storage, read> connections: array<Connection>;
@group(0) @binding(1) var<storage, read_write> nodes: array<Node>;
@group(0) @binding(2) var<storage, read_write> outputs: array<f32>;
@group(0) @binding(3) var<uniform> params: Params;
@group(0) @binding(4) var<storage, read> topoLevels: array<u32>;
@group(0) @binding(5) var<storage, read> inStart: array<u32>;

${activationFunctions}

fn applyActivation(x: f32) -> f32 {
  switch (ACTIVATION_INDEX) {
${supportedCases}
    default: { return x; }
  }
}

@compute @workgroup_size(${WORKGROUP_SIZE})
fn forward(@builtin(global_invocation_id) global_invocation_id: vec3<u32>) {
  let node_index = global_invocation_id.x;
  if (node_index >= params.node_count) {
    return;
  }

  if (topoLevels[node_index] != params.level) {
    return;
  }

  var pre_activation = nodes[node_index].derivative_state;
  let start = inStart[node_index];
  let end = inStart[node_index + 1u];

  for (var connection_index = start; connection_index < end; connection_index = connection_index + 1u) {
    let conn = connections[connection_index];
    if ((conn.flags & 1u) == 0u) {
      continue;
    }
    pre_activation = pre_activation + conn.weight * nodes[conn.from_node].activation_state;
  }

  let activated = applyActivation(pre_activation);
  nodes[node_index].activation_state = activated;
  outputs[node_index] = activated;
}
`;
}

/**
 * Generate the WGSL source for the activation kernel of a supported network.
 *
 * The returned source is a real, bindable compute shader: it declares six
 * storage-buffer/uniform bindings, the connection and node structs, one f32
 * activation function per supported worker index, and a `forward` entry point
 * that dispatches one thread per node for the current topological level.
 * Unsupported activations or ineligible topologies are rejected before any
 * source is emitted.
 *
 * @param network - Network whose activation index and topology are inspected.
 * @returns Non-empty WGSL source string.
 * @throws Error when the activation index is unsupported or the network
 *   topology is ineligible.
 *
 * @example
 * ```ts
 * const source = createActivationKernel(network);
 * const module = device.createShaderModule({ code: source });
 * ```
 */
export function createActivationKernel(network: Network): string {
  const activationIndex = readActivationIndex(network);

  if (
    !(SUPPORTED_ACTIVATION_INDICES as readonly number[]).includes(
      activationIndex,
    )
  ) {
    throw new Error(`activation index ${activationIndex} is not supported`);
  }

  return generateActivationSource(network);
}

/**
 * Internal slab-backed shape used only to read CSR source/target arrays for
 * topology hashing. Optional because some callers pass network shapes that do
 * not carry slab state.
 */
interface InternalSlabNetwork extends Network {
  /** Source node index per connection, when the slab has been materialized. */
  _connFrom?: Uint32Array;
  /** Target node index per connection, when the slab has been materialized. */
  _connTo?: Uint32Array;
}

/** Pipeline cache keyed by topology hash, scoped per device. */
const pipelineCache = new WeakMap<GPUDevice, Map<string, GPUComputePipeline>>();

/**
 * Return the per-device pipeline cache map, creating it on first use.
 */
function getDevicePipelineCache(
  device: GPUDevice,
): Map<string, GPUComputePipeline> {
  let cache = pipelineCache.get(device);
  if (!cache) {
    cache = new Map();
    pipelineCache.set(device, cache);
  }
  return cache;
}

/** Mix one integer into a simple 32-bit rolling hash. */
function mixHash(hash: number, value: number): number {
  return ((hash << 5) - hash + value) | 0;
}

/**
 * Compute a deterministic key that identifies the network topology.
 *
 * The key includes node and connection counts plus the CSR from/to arrays when
 * they are available. Networks that differ only in weights therefore share a
 * key, which is exactly the condition that lets the pipeline cache reuse the
 * same compiled shader.
 *
 * @param network - Network whose topology will be hashed.
 * @param activationIndex - Activation index that changes the generated shader.
 * @returns A stable string key for the pipeline cache.
 */
function computeTopologyKey(network: Network, activationIndex: number): string {
  const nodeCount = network.nodes.length;
  const connectionCount = network.connections.length;
  const slabNetwork = network as InternalSlabNetwork;

  if (slabNetwork._connFrom && slabNetwork._connTo) {
    const from = slabNetwork._connFrom;
    const to = slabNetwork._connTo;
    let hash = 0;
    for (let index = 0; index < from.length; index++) {
      hash = mixHash(hash, from[index]);
    }
    for (let index = 0; index < to.length; index++) {
      hash = mixHash(hash, to[index]);
    }
    return `${activationIndex}:${nodeCount}:${connectionCount}:${hash}`;
  }

  return `${activationIndex}:${nodeCount}:${connectionCount}`;
}

/**
 * Compile (or reuse) the activation compute pipeline for a network topology.
 *
 * The pipeline is created once per unique topology and cached on the supplied
 * device. Recompilations with identical topology but different weights reuse
 * the cached `GPUComputePipeline`, avoiding redundant compile stalls during
 * live inference. The shader module, bind-group layout, and pipeline creation
 * calls remain observable through a mock device for unit testing.
 *
 * @param device - WebGPU device used to compile the compute pipeline.
 * @param network - Network whose topology and activation index drive the kernel.
 * @returns A compute pipeline configured for the `forward` entry point.
 * @throws Error when the network has no nodes, lacks an activation index, or
 *   requests an unsupported activation.
 *
 * @example
 * ```ts
 * const pipeline = compileActivationKernel(device, network);
 * ```
 */
export function compileActivationKernel(
  device: GPUDevice,
  network: Network,
): GPUComputePipeline {
  const activationIndex = readActivationIndex(network);

  if (
    !(SUPPORTED_ACTIVATION_INDICES as readonly number[]).includes(
      activationIndex,
    )
  ) {
    throw new Error(`activation index ${activationIndex} is not supported`);
  }

  const topologyKey = computeTopologyKey(network, activationIndex);
  const cache = getDevicePipelineCache(device);
  const cached = cache.get(topologyKey);
  if (cached) {
    return cached;
  }

  const source = generateActivationSource(network);
  const shaderModule = device.createShaderModule({ code: source });
  const bindGroupLayout = createBindGroupLayout(device);
  const pipeline = buildGPUPipeline(device, shaderModule, bindGroupLayout);
  cache.set(topologyKey, pipeline);
  return pipeline;
}

/**
 * Create the bind-group layout used by the GPU forward-pass kernel.
 *
 * The layout exposes six entries in the exact order expected by the
 * struct-packed upload contract: the connection struct array, the node struct
 * array, the per-node output buffer, the per-dispatch params uniform, the
 * per-node topological level array, and the incoming-CSR start-offset array.
 *
 * @param device - WebGPU device used to create the layout.
 * @returns A bind-group layout with six entries.
 *
 * @example
 * ```ts
 * const bindGroupLayout = createBindGroupLayout(device);
 * ```
 */
export function createBindGroupLayout(device: GPUDevice): GPUBindGroupLayout {
  return device.createBindGroupLayout({
    entries: [
      {
        binding: 0,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 1,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'storage' },
      },
      {
        binding: 2,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'storage' },
      },
      {
        binding: 3,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'uniform' },
      },
      {
        binding: 4,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
      {
        binding: 5,
        visibility: GPU_SHADER_STAGE_COMPUTE,
        buffer: { type: 'read-only-storage' },
      },
    ],
  });
}

/**
 * Build a compute pipeline from a shader module and a bind-group layout.
 *
 * The pipeline uses the `forward` compute entry point and a pipeline layout
 * built from the supplied bind-group layout. It is the factory used by
 * `compileActivationKernel` to materialize the compiled GPU path.
 *
 * @param device - WebGPU device used to create the pipeline layout and pipeline.
 * @param shaderModule - Shader module containing the `forward` entry point.
 * @param bindGroupLayout - Layout describing the kernel's storage buffers.
 * @returns A compute pipeline configured for the forward-pass kernel.
 * @throws Error when pipeline creation fails.
 *
 * @example
 * ```ts
 * const pipeline = buildGPUPipeline(device, shaderModule, bindGroupLayout);
 * ```
 */
export function buildGPUPipeline(
  device: GPUDevice,
  shaderModule: GPUShaderModule,
  bindGroupLayout: GPUBindGroupLayout,
): GPUComputePipeline {
  const pipelineLayout = device.createPipelineLayout({
    bindGroupLayouts: [bindGroupLayout],
  });

  return device.createComputePipeline({
    layout: pipelineLayout,
    compute: {
      module: shaderModule,
      entryPoint: 'forward',
    },
  });
}
