import { createClient } from '@libsql/client';
import { searchCorpus, resetReadinessCaches } from './scripts/mcp-semantic/tools/search-corpus.mjs';
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'dbg-'));
const dbp = path.join(tmp, 'corpus.sqlite');
const db = createClient({ url: `file:${dbp}` });
await db.executeMultiple(`
CREATE TABLE documents (doc_id INTEGER PRIMARY KEY, doc_family TEXT NOT NULL, file_path TEXT NOT NULL, indexed_at INTEGER);
CREATE TABLE chunks (chunk_id INTEGER PRIMARY KEY, doc_id INTEGER, chunk_index INTEGER DEFAULT 0, heading_path TEXT, body_text TEXT, char_start INTEGER DEFAULT 0, char_end INTEGER DEFAULT 0, parent_chunk_id INTEGER, depth INTEGER DEFAULT 0, context_header TEXT, symbol_name TEXT, signature_text TEXT, jsdoc_text TEXT, export_type TEXT, module_path TEXT, arch_layer TEXT, jsdoc_quality TEXT, jsdoc_word_count INTEGER, cyclomatic_complexity INTEGER, test_coverage TEXT, source_path_pattern TEXT);
CREATE VIRTUAL TABLE chunks_fts USING fts5(body_text, content='chunks', content_rowid='chunk_id');
INSERT INTO documents VALUES (1, 'readme', 'README.md', 1);
INSERT INTO chunks (chunk_id, doc_id, body_text) VALUES (1, 1, 'fixture body text');
INSERT INTO chunks_fts (rowid, body_text) VALUES (1, 'fixture body text');
`);
await db.close();
process.env.DENSE_FORCE_STATE='cold';
process.env.RERANKER_FORCE_STATE='cold';
resetReadinessCaches();
const resp = await searchCorpus({ databasePath: dbp, query: 'fixture implementation', use_dense: false, limit: 5 });
console.log(JSON.stringify(resp, null, 2));
