// Pure ESM Jest configuration.
// We avoid CommonJS entirely; Jest 29+ supports loading ESM config (.mjs).

/** @type {import('jest').Config} */
const config = {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  // Use jsdom for asciiMaze browser example tests (pattern matching)
  testEnvironmentOptions: {},
  projects: [
    {
      displayName: 'default',
      testMatch: [
        '**/src/**/*.test.ts',
        '**/benchmarks/**/*.test.ts',
        '**/examples/**/*.test.ts',
        '**/testing/**/*.test.ts',
        '!**/examples/neatenstein/**',
      ],
      preset: 'ts-jest/presets/default-esm',
      testEnvironment: 'node',
      extensionsToTreatAsEsm: ['.ts'],
      moduleNameMapper: {
        '^neataptic$': '<rootDir>/src/neataptic.ts',
      },
      transform: {
        '^.+\\.ts$': [
          'ts-jest',
          { useESM: true, tsconfig: 'tsconfig.test.json', diagnostics: true },
        ],
        '^.+assimilate-repo\\.mjs$': [
          '<rootDir>/scripts/agent-customization/mcp/__tests__/mjs-cjs-transformer.cjs',
        ],
      },
      setupFilesAfterEnv: ['<rootDir>/testing/jest-setup.ts'],
      testTimeout: 300000,
      collectCoverageFrom: [
        '**/src/**/*.ts',
        '!**/src/**/*.d.ts',
        '!**/src/**/*.test.ts',
      ],
      coveragePathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
        '/examples/',
        '/scripts/',
        '/assimilate-repo',
        '/benchmarks/',
        '/testing/',
        '/rag-index/',
      ],
      coverageDirectory: 'coverage/project-default',
      coverageReporters: ['lcov', 'text', 'html', 'json', 'json-summary'],
      testPathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
        '/examples/asciiMaze/',
        '/examples/neatenstein/',
        '/examples/starter-examples.smoke.test.ts',
      ],
    },
    {
      displayName: 'neatenstein',
      testMatch: ['**/examples/neatenstein/**/*.test.ts'],
      preset: 'ts-jest/presets/default-esm',
      testEnvironment: 'node',
      extensionsToTreatAsEsm: ['.ts'],
      moduleNameMapper: {
        '^neataptic$': '<rootDir>/src/neataptic.ts',
      },
      transform: {
        '^.+\\.[tj]s$': [
          'ts-jest',
          {
            useESM: true,
            tsconfig: 'tsconfig.neatenstein.json',
            diagnostics: true,
          },
        ],
      },
      setupFilesAfterEnv: ['<rootDir>/testing/jest-setup.ts'],
      testTimeout: 300000,
      collectCoverageFrom: [
        'examples/neatenstein/browser-entry/browser-entry.ts',
        'examples/neatenstein/browser-entry/host/game/constants.ts',
        'examples/neatenstein/browser-entry/host/game/combat.ts',
        'examples/neatenstein/browser-entry/host/game/tick.ts',
        'examples/neatenstein/browser-entry/host/game/waves.ts',
        'examples/neatenstein/browser-entry/host/game/episode.ts',
        'examples/neatenstein/browser-entry/host/input.ts',
        'examples/neatenstein/browser-entry/host/game/controls.ts',
        'examples/neatenstein/browser-entry/host/renderer-bridge.ts',
        'examples/neatenstein/browser-entry/renderer/map.ts',
        'examples/neatenstein/browser-entry/renderer/raycast.ts',
        'examples/neatenstein/browser-entry/renderer/framebuffer.ts',
        'examples/neatenstein/browser-entry/renderer/walls.ts',
        'examples/neatenstein/browser-entry/renderer/sprites.ts',
        'examples/neatenstein/browser-entry/renderer/floor.ts',
        'examples/neatenstein/browser-entry/renderer/bolt-render.ts',
        'examples/neatenstein/browser-entry/renderer/gun.ts',
        'examples/neatenstein/browser-entry/renderer/gun-sprite.ts',
        'examples/neatenstein/browser-entry/constants.ts',
        'examples/neatenstein/browser-entry/harness/constants.ts',
        'examples/neatenstein/browser-entry/harness/enemy-mlp.ts',
        'examples/neatenstein/browser-entry/harness/enemy-warmstart.ts',
        'examples/neatenstein/browser-entry/harness/fitness.ts',
        'examples/neatenstein/browser-entry/harness/barrier.ts',
        'examples/neatenstein/browser-entry/harness/enemy-runner.ts',
        'examples/neatenstein/browser-entry/worker/display.worker.ts',
        'examples/neatenstein/scripts/*.ts',
        'examples/neatenstein/browser-entry/renderer/frame.ts',
        'examples/neatenstein/browser-entry/harness/arms-race.ts',
        'examples/neatenstein/browser-entry/harness/hive-density.ts',
        'examples/neatenstein/browser-entry/harness/main-runner.ts',
        'examples/neatenstein/browser-entry/worker/eval.worker.ts',
        'examples/neatenstein/browser-entry/harness/snapshot.ts',
        'examples/neatenstein/browser-entry/host/hud.ts',
        'examples/neatenstein/browser-entry/host/resize.ts',
        'examples/neatenstein/browser-entry/renderer/zbuffer.ts',
        'examples/neatenstein/browser-entry/host/game/cadence.ts',
        'examples/neatenstein/browser-entry/renderer/interpolate.ts',
        'examples/neatenstein/browser-entry/audio.ts',
        'examples/neatenstein/browser-entry/host/game/collision.ts',
      ],
      coveragePathIgnorePatterns: ['/node_modules/', '/dist/'],
      coverageDirectory: 'coverage/project-neatenstein',
      coverageReporters: ['lcov', 'text', 'html', 'json', 'json-summary'],
      testPathIgnorePatterns: ['/node_modules/', '/dist/'],
    },
    {
      displayName: 'asciiMaze-browser',
      testMatch: ['**/examples/asciiMaze/**/*.test.ts'],
      preset: 'ts-jest/presets/default-esm',
      testEnvironment: 'jsdom',
      extensionsToTreatAsEsm: ['.ts'],
      transform: {
        '^.+\\.ts$': [
          'ts-jest',
          { useESM: true, tsconfig: 'tsconfig.test.json', diagnostics: true },
        ],
      },
      setupFilesAfterEnv: ['<rootDir>/testing/jest-setup.ts'],
      testTimeout: 3000000,
      coveragePathIgnorePatterns: ['/examples/'],
    },
    {
      displayName: 'starter-examples',
      testMatch: ['**/examples/starter-examples.smoke.test.ts'],
      preset: 'ts-jest/presets/default-esm',
      testEnvironment: 'node',
      extensionsToTreatAsEsm: ['.ts'],
      transform: {
        '^.+\\.ts$': [
          'ts-jest',
          { useESM: true, tsconfig: 'tsconfig.test.json', diagnostics: true },
        ],
      },
      setupFilesAfterEnv: ['<rootDir>/testing/jest-setup.ts'],
      testTimeout: 300000,
      coveragePathIgnorePatterns: ['/examples/'],
    },
    {
      displayName: 'rag-index-scripts',
      testMatch: ['**/rag-index/**/*.test.ts'],
      preset: 'ts-jest/presets/default-esm',
      testEnvironment: 'node',
      extensionsToTreatAsEsm: ['.ts'],
      transform: {
        '^.+\\.ts$': [
          'ts-jest',
          { useESM: true, tsconfig: 'tsconfig.test.json', diagnostics: true },
        ],
      },
      setupFilesAfterEnv: ['<rootDir>/testing/jest-setup.ts'],
      testTimeout: 300000,
    },
    {
      displayName: 'agent-customization-scripts',
      testMatch: ['**/scripts/agent-customization/**/*.test.ts'],
      preset: 'ts-jest/presets/default-esm',
      testEnvironment: 'node',
      maxWorkers: 1,
      extensionsToTreatAsEsm: ['.ts'],
      transform: {
        '^.+\\.ts$': [
          'ts-jest',
          { useESM: true, tsconfig: 'tsconfig.test.json', diagnostics: true },
        ],
        '^.+\\.mjs$': [
          '<rootDir>/scripts/agent-customization/mcp/__tests__/mjs-cjs-transformer.cjs',
        ],
      },
      setupFilesAfterEnv: ['<rootDir>/testing/jest-setup.ts'],
      testTimeout: 300000,
      collectCoverageFrom: [
        'scripts/agent-customization/**/*.mjs',
        'scripts/agent-customization/**/*.ts',
        '!scripts/agent-customization/**/*.test.mjs',
        '!scripts/agent-customization/**/*.test.ts',
        '!scripts/agent-customization/**/__red__*.mjs',
        '!scripts/agent-customization/**/gate-test-utils.mjs',
        '!scripts/agent-customization/mcp/__tests__/**',
      ],
      coverageDirectory: 'coverage/project-agent-customization-scripts',
      coverageReporters: ['lcov', 'text', 'html', 'json', 'json-summary'],
    },
    {
      displayName: 'agent-customization-mjs',
      testMatch: ['**/scripts/agent-customization/**/*.test.mjs'],
      testEnvironment: 'node',
      transform: {},
      coverageDirectory: 'coverage/project-agent-customization-mjs',
      coverageReporters: ['lcov', 'text', 'html', 'json', 'json-summary'],
      collectCoverageFrom: [
        'scripts/agent-customization/**/*.mjs',
        '!scripts/agent-customization/**/*.test.mjs',
        '!scripts/agent-customization/**/__red__*.mjs',
        '!scripts/agent-customization/**/gate-test-utils.mjs',
        '!scripts/agent-customization/mcp/__tests__/**',
      ],
      testPathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
        '/scripts/agent-customization/mcp/__tests__/',
      ],
      testTimeout: 300000,
    },
    {
      displayName: 'mcp-semantic-scripts',
      testMatch: ['**/scripts/mcp-semantic/**/*.test.ts'],
      preset: 'ts-jest/presets/default-esm',
      testEnvironment: 'node',
      extensionsToTreatAsEsm: ['.ts'],
      transform: {
        '^.+\\.ts$': [
          'ts-jest',
          { useESM: true, tsconfig: 'tsconfig.test.json', diagnostics: true },
        ],
      },
      setupFilesAfterEnv: ['<rootDir>/testing/jest-setup.ts'],
      testTimeout: 300000,
      collectCoverageFrom: [
        'scripts/mcp-semantic/tools/submit-feedback.mjs',
        'scripts/mcp-semantic/tools/cortex-db.mjs',
      ],
      coverageDirectory: 'coverage/project-mcp-semantic-scripts',
      coverageReporters: ['lcov', 'text', 'html', 'json', 'json-summary'],
    },
    {
      displayName: 'rag-index-mjs',
      testMatch: ['**/rag-index/**/*.test.mjs'],
      testEnvironment: 'node',
      transform: {},
      testTimeout: 600000,
      collectCoverageFrom: [
        'rag-index/**/*.mjs',
        '!rag-index/**/*.test.mjs',
        '!rag-index/**/__tests__/*.test.mjs',
      ],
      coverageDirectory: 'coverage/project-rag-index-mjs',
      coverageReporters: ['lcov', 'text', 'html', 'json', 'json-summary'],
    },
    {
      displayName: 'mcp-semantic-mjs',
      testMatch: ['**/scripts/mcp-semantic/**/*.test.mjs'],
      testEnvironment: 'node',
      transform: {},
      testTimeout: 300000,
      setupFilesAfterEnv: ['<rootDir>/testing/jest-setup-mcp-semantic.mjs'],
      collectCoverageFrom: [
        'scripts/mcp-semantic/**/*.mjs',
        '!scripts/mcp-semantic/**/*.test.mjs',
        '!scripts/mcp-semantic/**/__tests__/**',
      ],
      coverageDirectory: 'coverage/project-mcp-semantic-mjs',
      coverageReporters: ['lcov', 'text', 'html', 'json', 'json-summary'],
    },
    {
      displayName: 'analyze-trace-scripts',
      testMatch: ['**/scripts/analyze-trace/**/*.test.ts'],
      preset: 'ts-jest/presets/default-esm',
      testEnvironment: 'node',
      extensionsToTreatAsEsm: ['.ts'],
      moduleNameMapper: {
        '^(\\.{1,2}/.*)\\.js$': '$1',
      },
      transform: {
        '^.+\\.ts$': [
          'ts-jest',
          { useESM: true, tsconfig: 'tsconfig.test.json', diagnostics: true },
        ],
      },
      setupFilesAfterEnv: ['<rootDir>/testing/jest-setup.ts'],
      testTimeout: 300000,
      collectCoverageFrom: [
        'scripts/analyze-trace/analyze-trace.io.ts',
        'scripts/analyze-trace/analyze-trace.ts',
        'scripts/analyze-trace/analyze-trace.shared.ts',
        'scripts/analyze-trace/analyze-trace.report.ts',
        'scripts/analyze-trace/analyze-trace.constants.ts',
        'scripts/analyze-trace/analyze-trace.analysis.ts',
      ],
    },
    {
      displayName: 'trace-scripts-mjs',
      testMatch: ['**/scripts/trace-*.test.mjs'],
      testEnvironment: 'node',
      transform: {},
      testTimeout: 300000,
      collectCoverageFrom: [
        'scripts/trace-compress.mjs',
        'scripts/trace-summarize.mjs',
      ],
    },
  ],
  testMatch: [
    '**/src/**/*.test.ts',
    '**/benchmarks/**/*.test.ts',
    '**/examples/**/*.test.ts',
    '**/testing/**/*.test.ts',
  ],
  moduleFileExtensions: ['ts', 'js', 'mjs', 'cjs', 'json'],
  extensionsToTreatAsEsm: ['.ts'],
  moduleNameMapper: {
    '^neataptic$': '<rootDir>/src/neataptic.ts',
  },
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        useESM: true,
        tsconfig: 'tsconfig.test.json',
        diagnostics: true,
      },
    ],
  },
  setupFilesAfterEnv: ['<rootDir>/testing/jest-setup.ts'],
  testTimeout: 300000,
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  modulePathIgnorePatterns: ['/dist/'],
};

export default config;
