/**
 * Additional conversational lines used to build the shipped default NEATchat snapshot.
 *
 * The existing sample conversation establishes one casual social voice. This
 * larger corpus broadens the default snapshot with scheduling, troubleshooting,
 * planning, explanation, and reflective dialogue so the browser starts from a
 * stronger general-purpose checkpoint instead of a near-blank session.
 */
export const DEFAULT_NEATCHAT_PRETRAINING_CORPUS_LINES: readonly string[] = [
  'Hello, how are you doing today?',
  'I am doing well, thank you for asking. How are you?',
  'I am feeling pretty good this morning, thanks.',
  'That is nice to hear from you today.',
  'Yes, the weather is really pleasant outside right now.',
  'I noticed the sunshine when I woke up this morning.',
  'Did you sleep well last night or were you up late?',
  'I slept okay, but I woke up a little earlier than usual.',
  'Sometimes I wake up early too, especially on weekends.',
  'I usually try to sleep in, but it does not always work out.',
  'Did you have anything for breakfast yet this morning?',
  'Yes, I had some toast and a cup of tea before work.',
  'That sounds like a simple and easy breakfast to make.',
  'It was quick and easy, which I really like in the morning.',
  'I had some cereal with milk for my breakfast today.',
  'Cereal is always a good choice for a quick breakfast.',
  'Do you usually eat breakfast at home every day?',
  'Yes, I almost always eat at home in the mornings.',
  'I sometimes grab something on my way to work if I am late.',
  'That is convenient if you are in a hurry to get going.',
  'Yes, it saves me a little time in the morning rush.',
  'Do you have any plans for today or are you taking it easy?',
  'I am planning to go for a walk in the park later today.',
  'That sounds like a relaxing way to spend your afternoon.',
  'I enjoy being outside when the weather is nice and sunny.',
  'I like to walk in the park too, especially in the springtime.',
  'The flowers are starting to bloom everywhere right now.',
  'I saw some beautiful tulips near my house yesterday afternoon.',
  'Tulips are one of my favorite flowers in the spring season.',
  'I like daffodils too, they are so bright and cheerful to see.',
  'Do you have any plants at home or just outside in the yard?',
  'Yes, I have a few small plants on my windowsill at home.',
  'I have a cactus and a little fern in my kitchen right now.',
  'Cacti are easy to take care of, which is really nice for me.',
  'I sometimes forget to water my plants, so cacti are perfect.',
  'Do you have any pets at home or are you thinking about it?',
  'No, I do not have any pets right now in my apartment.',
  'I have a cat named Milo who loves to nap all day long.',
  'That sounds adorable, I really love cats a lot.',
  'Milo is very friendly and always wants attention from me.',
  'I wish I could have a pet, but my apartment does not allow them.',
  'That is too bad, but maybe someday you can get one for yourself.',
  'I hope so, because I really like animals and want a pet.',
  'Do you like dogs or cats more, or do you like both equally?',
  'I like both, but I think I am more of a cat person overall.',
  'I like both too, but I have always wanted to have a dog.',
  'Dogs are great companions, especially for going on walks together.',
  'Yes, I see people walking their dogs in the park every morning.',
  'It looks like a nice way to start the day with some fresh air.',
  'I agree, fresh air and exercise are always good for your health.',
  'Do you like to exercise regularly or just when you have time?',
  'I try to go for a walk or do some stretching every single day.',
  'That is a good habit to have for your health and well-being.',
  'I sometimes do yoga at home when I have a little extra time.',
  'Yoga is very relaxing and helps with stress after a long day.',
  'I like how calm I feel after a good yoga session at home.',
  'Do you prefer to exercise alone or with friends in a group?',
  'I usually exercise alone, but sometimes I join a group class.',
  'Group classes can be motivating and a lot of fun together.',
  'Yes, I like the energy of being around other people sometimes.',
  'Do you listen to music while you exercise or walk outside?',
  'Yes, I always listen to music when I go for a walk outside.',
  'Music makes everything more enjoyable, I really think so too.',
  'I agree, it helps me keep a good pace and stay motivated.',
  'What kind of music do you like to listen to the most?',
  'I like pop music and sometimes a little bit of rock as well.',
  'I listen to a lot of different genres, depending on my mood.',
  'That is a good way to keep things interesting and fresh.',
  'Do you play any musical instruments or want to learn one?',
  'No, but I have always wanted to learn how to play the guitar.',
  'I play a little bit of piano, but I am still learning right now.',
  'Piano music is very beautiful and soothing to listen to.',
  'I like to play simple songs when I have some free time.',
  'Do you like to sing along to music when you are at home?',
  'I sing sometimes, but only when I am alone in my apartment.',
  'I do the same, especially when I am in the shower at home.',
  'Singing in the shower is always fun and very relaxing for me.',
  'Do you like to dance as well, or do you prefer just listening?',
  'I like to dance, but I am not very good at it to be honest.',
  'I am not a great dancer either, but I enjoy moving to music.',
  'It is more about having fun than being perfect at dancing.',
  'Exactly, I think everyone should dance sometimes for fun.',
  'Do you like to watch movies in your free time at home?',
  'Yes, I love watching movies, especially on the weekends.',
  'What kind of movies do you enjoy watching the most?',
  'I like comedies and adventure movies the best right now.',
  'I enjoy comedies too, they always make me laugh a lot.',
  'Laughter is good for the soul, I really believe that.',
  'Do you prefer watching movies at home or in the cinema?',
  'I usually watch movies at home because it is more comfortable.',
  'I like the cinema for big action movies, but home is cozier.',
  'Do you like to eat snacks while watching movies at home?',
  'Yes, I always have popcorn or chips when I watch a movie.',
  'Popcorn is my favorite movie snack, especially with butter.',
  'Do you prefer salty or sweet popcorn when you watch movies?',
  'I like salty popcorn with a little bit of butter on top.',
  'I like sweet popcorn sometimes, but salty is my favorite.',
  'Do you like to cook your own meals at home most days?',
  'I cook simple meals most days, but I am not a great chef.',
  'Cooking at home is healthier and can be a lot of fun too.',
  'I agree, I like trying new recipes when I have extra time.',
  'What is your favorite dish to cook for yourself or others?',
  'I like making pasta because it is easy and always delicious.',
  'Pasta is always a good choice for a quick and tasty meal.',
  'Do you like to bake as well as cook regular meals?',
  'I do not bake often, but I enjoy making cookies sometimes.',
  'Cookies are always a treat, especially when they are fresh.',
  'Do you have a favorite type of cookie to bake or eat?',
  'Chocolate chip cookies are my favorite by far, they are classic.',
  'I love chocolate chip cookies too, they are always delicious.',
  'Do you like to eat fruit for dessert after your meals?',
  'Yes, I often have fruit after dinner because it is healthy.',
  'Fruit is a healthy and tasty dessert option for any meal.',
  'I like apples and bananas the most for a quick snack.',
  'I enjoy berries, especially strawberries and blueberries.',
  'Berries are delicious and full of vitamins for your health.',
  'Do you like to drink tea or coffee more in the mornings?',
  'I drink tea in the morning and sometimes coffee in the afternoon.',
  'I usually have coffee in the morning to help me wake up.',
  'Coffee is a good way to start the day for many people.',
  'Do you take your coffee with milk or sugar, or just black?',
  'I like a little milk in my coffee, but I do not add sugar.',
  'I drink my coffee black most of the time, no milk or sugar.',
  'That is strong, but some people really prefer it that way.',
  'Do you like to read books in your free time at home?',
  'Yes, I read almost every day before I go to bed at night.',
  'Reading is a great way to relax and unwind after a long day.',
  'What kind of books do you enjoy reading the most?',
  'I like fiction, especially mysteries and adventure stories.',
  'I enjoy mysteries too, they always keep me guessing.',
  'Do you have a favorite author or do you read many different ones?',
  'I do not have one favorite, but I like many different writers.',
  'I feel the same way, there are so many good books out there.',
  'Do you prefer paper books or e-books for your reading?',
  'I like paper books because I enjoy turning the pages by hand.',
  'I use e-books because they are easy to carry around everywhere.',
  'Both have their advantages, I think it depends on the situation.',
  'Do you like to write as well as read books?',
  'I sometimes write short stories for fun when I have time.',
  'That is very creative, I admire people who write stories.',
  'Writing helps me organize my thoughts and express myself better.',
  'Do you keep a journal or diary to write about your day?',
  'I try to write in a journal a few times a week if I remember.',
  'Journaling is a good way to reflect on your day and feelings.',
  'It helps me remember important moments and how I felt.',
  'Do you like to draw or paint pictures in your free time?',
  'I like to draw simple pictures, but I am not very skilled at it.',
  'Drawing is relaxing, even if you are not a professional artist.',
  'I agree, it is about enjoying the process and having fun.',
  'Do you like to do puzzles or play games when you are bored?',
  'I enjoy doing puzzles, especially on rainy days at home.',
  'Puzzles are a good way to keep your mind sharp and focused.',
  'I also like playing board games with friends and family.',
  'Board games are fun and bring people together for a good time.',
  'Do you like to play card games with your family or friends?',
  'Yes, I play cards with my family sometimes on weekends.',
  'Card games are a great way to spend time together and laugh.',
  'Do you like to travel to new places when you have the chance?',
  'I love traveling, but I do not get to do it very often.',
  'Traveling is exciting and helps you learn about new cultures.',
  'Where would you like to visit someday if you could go anywhere?',
  'I would love to visit Japan and see the cherry blossoms in spring.',
  'Japan is a beautiful country with a rich history and culture.',
  'Do you prefer the beach or the mountains for a vacation?',
  'I like the beach because I enjoy swimming and relaxing in the sun.',
  'I prefer the mountains for hiking and getting fresh air outdoors.',
  'Both are wonderful in their own ways and offer something special.',
  'Do you like to swim in the ocean or do you prefer pools?',
  'I like swimming, but I am a little afraid of big waves in the ocean.',
  'I understand, the ocean can be powerful and a little scary sometimes.',
  'Do you like to go hiking in nature when you have free time?',
  'Yes, I enjoy hiking in nature whenever I can get away.',
  'Hiking is a great way to clear your mind and get some exercise.',
  'Do you like to camp outdoors or do you prefer staying indoors?',
  'I have only camped a few times, but I enjoyed it when I did.',
  'Camping is fun, but I miss my comfortable bed at home.',
  'I agree, sleeping bags are not as cozy as a real bed at home.',
  'Do you like to watch the stars at night when the sky is clear?',
  'Yes, I love looking at the stars on clear nights outside.',
  'Stargazing is peaceful and makes me feel calm and relaxed.',
  'Do you like to watch the sunrise or sunset more?',
  'I prefer sunsets because I am not really a morning person.',
  'Sunsets are beautiful and a nice way to end the day.',
  'Do you like to take photographs of nature or people?',
  'I enjoy taking photos of nature and interesting places I visit.',
  'Photography is a wonderful hobby for capturing memories.',
  'Do you like to visit museums or art galleries when you travel?',
  'I like visiting museums, especially when I am in a new city.',
  'Museums are interesting and full of history and culture.',
  'Do you like to learn about history or do you prefer science?',
  'Yes, I find history fascinating and important to understand.',
  'Learning about the past helps us understand the present better.',
  'I think I prefer science because it explains how things work.',
  'Science is very interesting and always changing with new discoveries.',
  'I watch documentaries when I want to learn something new.',
  'Documentaries are a great way to discover new topics and ideas.',
  'I like cooking with friends because it is more fun than cooking alone.',
  'Cooking together makes the meal taste even better and more special.',
  'I enjoy trying new foods, but I am not very adventurous with spicy dishes.',
  'Trying new foods can be exciting and sometimes surprising.',
  'I do not like very spicy food, but a little spice is okay for me.',
  'I like mild spice, but nothing too hot or overwhelming.',
  'I like going to restaurants for special occasions with friends.',
  'Eating out is a nice treat once in a while, but I prefer home-cooked meals.',
  'I enjoy celebrating birthdays with family and friends every year.',
  'Birthdays are a good reason to eat cake and have some fun together.',
  'I like giving gifts more than receiving them because it makes people happy.',
  'Giving gifts shows you care and makes the other person feel special.',
  'I always try to help people if I am able to do so.',
  'Helping others is important and makes the world a better place.',
  'I have volunteered a few times and found it very rewarding.',
  'Volunteering is a great way to meet people and make a difference.',
  'I enjoy both spending time alone and being with others, depending on my mood.',
  'Spending time alone helps me recharge my energy after a busy day.',
  'I try to plan my week so I do not forget important things I need to do.',
  'Planning ahead helps me stay organized and feel less stressed.',
  'I make lists for everything because it helps me remember my tasks.',
  'Lists are helpful for keeping track of what needs to be done each day.',
  'I set small goals to keep myself motivated and moving forward.',
  'Setting goals gives me something to work towards and achieve.',
  'I enjoy learning new things whenever I have the chance to do so.',
  'Learning new skills keeps life interesting and exciting for me.',
  'I check the news in the morning to stay informed about the world.',
  'Staying informed is important, but sometimes the news is stressful to read.',
  'I try not to watch too much news so I do not feel overwhelmed.',
  'I often have tea in the evening to help me unwind and relax.',
  'Tea is calming and a nice way to end the day before bed.',
  'I listen to podcasts when I am walking or cleaning around the house.',
  'Podcasts are a great way to learn and be entertained at the same time.',
  'I love laughing with friends because it makes me feel happy and light.',
  'Laughter is the best medicine, as people always say.',
  'I am not very good at telling jokes, but I try to make people laugh.',
  'Telling jokes is fun, even if they are a little silly sometimes.',
  'I enjoy playing games with my younger cousins when they visit.',
  'Playing with children is always full of energy and laughter for everyone.',
  'I try to visit my family as much as I can, especially on holidays.',
  'Family time is important and always makes me feel loved and supported.',
  'I prefer texting because it is quick and easy for most conversations.',
  'Texting is convenient, but sometimes I like to hear a real voice.',
  'I write emails for work, but letters are more personal and special.',
  'Writing letters is special, but I do not do it very often these days.',
  'I like to keep my room tidy and organized so I can think clearly.',
  'A clean space helps me feel more relaxed and focused on my work.',
  'I enjoy decorating with simple things like plants and pictures at home.',
  'Decorating makes a space feel more comfortable and personal to me.',
  'I shop for clothes when I need something new or for a special event.',
  'Shopping can be fun, but I do not do it very often these days.',
  'I sometimes try new styles, but I usually stick to what I like best.',
  'Trying new styles can be exciting and refreshing for your wardrobe.',
  'I usually wear neutral tones, but sometimes I like bright colors too.',
  'Bright colors can make you feel cheerful and confident all day.',
  'I like wearing scarves in the winter to stay warm and cozy.',
  'Scarves are cozy and add a nice touch to any outfit you wear.',
  'I wear simple jewelry, nothing too flashy or heavy for everyday use.',
  'Simple jewelry is elegant and easy to wear every single day.',
  'I go to the hairdresser every few months for a trim and refresh.',
  'Getting a haircut always feels refreshing and gives me a new look.',
  'I sometimes try new hairstyles, but I usually keep it simple and easy.',
  'Simple hairstyles are easy to manage and look nice for any occasion.',
  'I watch sports sometimes, especially with friends or family at home.',
  'Watching sports is more fun with a group of people cheering together.',
  'I play badminton with friends on weekends when the weather is nice.',
  'Badminton is a fun and active game to play with friends or family.',
  'I do not go to the gym, but I exercise at home with online videos.',
  'Exercising at home is convenient and comfortable for my schedule.',
  'I enjoy riding my bike in the park when the weather is nice outside.',
  'Biking is a great way to explore and get some exercise at the same time.',
  'I like long drives in the countryside with good music playing in the car.',
  'Long drives are relaxing and give you time to think and unwind.',
  'I like trying new restaurants with friends on weekends for something different.',
  'Trying new food is always an adventure and can be a lot of fun.',
  'Cooking with family is fun and brings everyone together in the kitchen.',
  'Family meals are special and full of good memories for everyone.',
  'I enjoy celebrating holidays with family and friends every year.',
  'Holidays are a time for joy and togetherness with the people you love.',
  'I like putting up simple decorations for each holiday at home.',
  'Decorating makes the holiday feel more festive and fun for everyone.',
  'I enjoy making simple crafts, especially during the holidays with family.',
  'Crafting is a creative way to spend time and make gifts for others.',
  'I like to paint with watercolors when I have free time on weekends.',
  'Watercolor painting is relaxing and lets me express my creativity.',
];
