/**
 * Shared scripted conversation corpus used by the NEATchat demo.
 *
 * One interaction per line, ordered as a natural alternating dialogue.
 * The browser can pretrain from this corpus with a single action, and tests
 * can reuse the same source so behavior checks stay reproducible.
 */
export const NEATCHAT_SAMPLE_CONVERSATION_LINES: readonly string[] = [
  'Hi, how was your day?',
  'It was pretty good, thanks for asking. How about yours?',
  'Not too bad. I had a lot of meetings, but I managed to get through them.',
  'Meetings can be exhausting. Did anything interesting happen?',
  'Actually, yes. One of the meetings was about a new project we might start next month.',
  'That sounds exciting! What kind of project is it?',
  "It's a collaboration with another department to develop a new app.",
  "Wow, that's cool. Are you going to be leading the project?",
  "I'm not sure yet, but I hope so. I've always wanted to manage something like this.",
  "You'd be great at it. You're organized and creative.",
  'Thanks, that means a lot. What about you? Any news at work?',
  "Nothing major, but I did finish a big report I'd been working on for weeks.",
  "That's a relief, I bet. Was it stressful?",
  'A little, but mostly I just wanted to make sure everything was perfect.',
  'I know the feeling. Sometimes I double-check things too much.',
  'Better to be thorough than to miss something important.',
  'True. Do you have any plans for the weekend?',
  'Not really. I was thinking of just relaxing at home. You?',
  "I might go hiking if the weather's nice. Want to join?",
  "That sounds fun! I haven't been hiking in ages.",
  "It's a great way to clear your mind. Plus, the views are amazing.",
  'Where do you usually go?',
  "There's a trail about an hour from here. It's not too difficult, but the scenery is beautiful.",
  "I'd love to check it out. Should we bring snacks?",
  "Definitely. I'll pack some sandwiches and fruit.",
  'I can bring water and maybe some energy bars.',
  'Perfect. What time should we leave?',
  'How about 9 a.m.? That way we can avoid the midday heat.',
  'Sounds good to me. Should we invite anyone else?',
  'Maybe. Do you think Sarah would want to come?',
  "She might. I'll text her and see if she's interested.",
  'Great. The more, the merrier.',
  'Agreed. Do you remember the last time we all went hiking?',
  'Yeah, it was last spring. We got caught in that rainstorm.',
  'That was wild! We were soaked by the time we got back to the car.',
  'But it was still a lot of fun. We laughed the whole way.',
  'Sometimes the unexpected moments are the best.',
  'Absolutely. Speaking of unexpected, did you hear about the new restaurant opening downtown?',
  "No, I hadn't. What kind of food do they serve?",
  "It's a fusion place-mix of Asian and Mediterranean.",
  'That sounds delicious. We should try it sometime.',
  "I'm in! Maybe after our hike?",
  "Great idea. We'll probably be hungry.",
  "For sure. I'll make a reservation just in case.",
  "Good thinking. It's probably going to be busy.",
  'Yeah, new places always are. I hope the food lives up to the hype.',
  'Me too. I love trying new things.',
  'Same here. It keeps life interesting.',
  'So, what else is new with you?',
  "Not much, honestly. I've been reading a lot lately.",
  'Anything good?',
  'I just finished a mystery novel. It was a real page-turner.',
  'I love mysteries. Who was the author?',
  'Her name is Lisa Gardner. Have you read any of her books?',
  "I don't think so. Would you recommend it?",
  'Definitely. The plot twists kept me guessing until the end.',
  "I'll have to check it out. I've been looking for something new to read.",
  'I can lend you my copy if you want.',
  "Thanks! I'll take you up on that.",
  'No problem. What kind of books do you usually like?',
  'Mostly thrillers and historical fiction.',
  "Nice. I like those too. There's something about getting lost in another time.",
  "Exactly. It's like traveling without leaving your chair.",
  'Well said. Do you ever listen to audiobooks?',
  "Sometimes, especially when I'm driving.",
  "They're great for long commutes. I listened to one last week that was really good.",
  'Which one?',
  'It was The Night Circus by Erin Morgenstern.',
  "I've heard of that! Did you like it?",
  'I loved it. The narration was fantastic.',
  "I'll add it to my list. Thanks for the recommendation.",
  'Anytime. So, have you watched any good movies lately?',
  'I saw Dune last weekend. It was amazing.',
  "I've been meaning to watch that. Was it true to the book?",
  'Pretty much. They did a great job with the visuals.',
  "I'll have to see it soon. Maybe we can watch it together.",
  'That would be fun. Movie night?',
  'Absolutely. Popcorn is on me.',
  'Deal. Do you prefer sweet or salty popcorn?',
  'Salty, with a little butter.',
  'Same here. Classic is best.',
  'Agreed. Do you want to watch at your place or mine?',
  "Let's do mine. I just got a new sound system.",
  "Nice! I can't wait to hear it.",
  'It makes a big difference, especially for action scenes.',
  'I bet. So, hiking in the morning, movie night in the evening?',
  'Sounds like a perfect day.',
  "I'm looking forward to it.",
  "Me too. It's been a while since we hung out like this.",
  "Yeah, life gets busy. It's good to slow down sometimes.",
  'Definitely. We should make it a regular thing.',
  "I'd like that. Maybe once a month?",
  "Let's do it. We can take turns planning.",
  'Great idea. Keeps things interesting.',
  "Exactly. So, what's your favorite way to relax?",
  'Honestly, just sitting outside with a cup of coffee.',
  'That sounds nice. Do you have a favorite spot?',
  "There's a little park near my apartment. It's quiet and peaceful.",
  "I'll have to check it out sometime.",
  "You should. It's a hidden gem.",
  'I love finding places like that.',
  "Me too. It's important to have a place to unwind.",
  'Absolutely. Especially with how hectic life can be.',
  "Yeah. Sometimes I feel like I'm always rushing.",
  "Same here. That's why I try to make time for myself.",
  "It's important. Self-care isn't selfish.",
  'Agreed. What do you do to take care of yourself?',
  'I like to cook. Trying new recipes is relaxing for me.',
  "That's awesome. What's your favorite dish to make?",
  'Probably homemade pasta. Its a bit of work, but so worth it.',
  "I've never made pasta from scratch. Is it hard?",
  'Not really, just takes some patience.',
  'Maybe you can teach me sometime.',
  "I'd love to. We can have a cooking night.",
  "That sounds fun. I'll bring dessert.",
  "Deal. What's your specialty?",
  "Chocolate cake. It's my grandmother's recipe.",
  "Now I'm hungry.",
  'Me too. Maybe we should grab dinner.',
  'Good idea. Where should we go?',
  'How about that little Italian place on Main Street?',
  "Perfect. I've been craving pizza.",
  "Me too. Let's go.",
  "I'll drive.",
  "Thanks. I'll get the door.",
  'After you.',
  'Thank you. So, whats your favorite pizza topping?',
  'Mushrooms and olives. You?',
  'Pepperoni and extra cheese.',
  "Classic choice. Can't go wrong.",
  'Exactly. Do you want to share a pizza?',
  'Sure. Half and half?',
  'Sounds good to me.',
  "Great. I'll let the waiter know.",
  'Thanks. So, tell me more about your new project at work.',
  "Well, it's still in the early stages, but we're brainstorming ideas.",
  "That's exciting. Do you have any concepts in mind?",
  'A few. We want to focus on user experience.',
  "That's important. People appreciate intuitive design.",
  "Exactly. We're thinking of doing some user testing.",
  'Smart move. Feedback is valuable.',
  "Definitely. I'll keep you posted as things develop.",
  "Please do. I'm curious to see how it turns out.",
  'Thanks for your support.',
  "Always. That's what friends are for.",
  'True. I appreciate it.',
  'Anytime. So, whats one thing you want to do this year?',
  "Travel more. I haven't been anywhere new in a while.",
  'Where would you go if you could pick anywhere?',
  "Japan. I've always wanted to see the cherry blossoms.",
  'That would be amazing. I hope you get to go.',
  'Me too. What about you?',
  "I'd like to learn a new language.",
  'Which one?',
  'Spanish, maybe. Its useful and beautiful.',
  'Good choice. There are lots of resources online.',
  "Yeah, I've started using an app.",
  "How's it going?",
  'Slow but steady. Practice makes perfect.',
  'Exactly. Maybe we can practice together.',
  'That would be great. Two heads are better than one.',
  "Agreed. Let's set a goal.",
  'How about learning a new phrase each week?',
  "Perfect. We'll quiz each other.",
  'Deal. This will be fun.',
  "I'm looking forward to it.",
  "Me too. It's good to challenge ourselves.",
  'Absolutely. Keeps the mind sharp.',
  "So, what's your favorite way to spend a Sunday?",
  'Sleeping in, then brunch with friends.',
  'That sounds perfect.',
  'It is. How about you?',
  'I like to go for a run, then read.',
  'Nice. Do you run often?',
  'A few times a week. It helps me clear my head.',
  "That's great. I wish I had your motivation.",
  'You can join me anytime.',
  'Maybe I will. I could use the exercise.',
  "It's more fun with a friend.",
  "Agreed. Let's plan for next Sunday.",
  "Sounds good. I'll remind you.",
  "Thanks. I'll need it.",
  "No problem. So, what's one thing you're grateful for today?",
  'This conversation.',
  "Me too. It's nice to connect.",
  'Absolutely. Thanks for being here.',
  'Always.',
  'Hey, are you free to talk for a minute?',
  'Sure. What do you want to figure out?',
  'I am trying to plan my week without feeling overloaded.',
  'Start with the deadlines that cannot move, then protect recovery time around them.',
  'That makes sense. I keep putting everything on the same day.',
  'Try spreading hard tasks across the week so no single day carries all the pressure.',
  'Do you usually plan in detail or just set priorities?',
  'I set three priorities first, then I add smaller tasks if there is room.',
  'I like that. It sounds more realistic than a giant checklist.',
  'It is. A short honest plan is better than an ambitious one you abandon by noon.',
  'My laptop has been slow all morning and I cannot tell why.',
  'Check whether one browser tab or background process is using most of the memory.',
  'I already closed a few tabs, but it still feels sluggish.',
  'Then restart the app with the highest usage and see whether the lag drops.',
  'If that does not help, what would you try next?',
  'I would look for a pending update or a sync task quietly running in the background.',
  'Good point. I forget that file syncing can slow everything down.',
  'It often does, especially when large folders are changing all at once.',
  'I want to cook something simple tonight, but not the same thing as always.',
  'What ingredients do you already have at home?',
  'Rice, eggs, spinach, onions, and a little bit of cheese.',
  'That is enough for fried rice or a quick baked rice bowl.',
  'I was hoping for something easy to clean up too.',
  'Then use one pan, keep the seasoning simple, and add the cheese at the end.',
  'That actually sounds perfect.',
  'It should be fast, filling, and low effort.',
  'I keep losing focus when I read longer articles.',
  'Try reading with one question in mind so your attention has a target.',
  'So instead of reading passively, I should look for an answer?',
  'Exactly. Curiosity makes it easier to stay engaged with dense material.',
  'Do you ever take notes while reading?',
  'Yes, but I keep them short. I only write what I will want to remember tomorrow.',
  'That sounds more sustainable than copying whole paragraphs.',
  'It is. Notes should reduce friction, not create more of it.',
  'I have a meeting later and I am not sure how direct I should be.',
  'Be clear about the problem, but give people room to respond without feeling cornered.',
  'So name the issue and the impact, then ask how they see it?',
  'Yes. That keeps the conversation constructive instead of defensive.',
  'I tend to soften things too much and then nobody knows what I mean.',
  'Clarity is kinder than vagueness when everyone is trying to solve the same problem.',
  'I needed to hear that.',
  'Most people do. Direct and respectful beats indirect and confusing.',
  'I am thinking about starting a new hobby this month.',
  'Do you want something relaxing, social, or skill-building?',
  'Probably skill-building, but still enjoyable enough to keep doing.',
  'Then pick something with visible progress, like drawing, cooking, or learning songs.',
  'Visible progress is important for me.',
  'It keeps motivation alive when the novelty fades.',
  'How do you stay consistent with hobbies?',
  'I make them easy to start. Ten minutes beats waiting for the perfect free afternoon.',
  'That is probably where I get stuck.',
  'Most habits fail at the starting line, not the finish line.',
  'I slept badly last night and now everything feels harder.',
  'Then lower the bar for today and protect the essentials first.',
  'You mean do less on purpose?',
  'Yes. Fatigue changes what a good day looks like.',
  'I always fight that idea because it feels lazy.',
  'It is not lazy. It is adapting to the reality you actually have.',
  'That framing helps a lot.',
  'Good. Flexibility is a skill, not a failure.',
  'Can you help me phrase a polite follow-up email?',
  'Sure. Keep it short, specific, and easy to answer.',
  'I do not want to sound impatient.',
  'You can say you are checking in on timing and that you appreciate any update they can share.',
  'That sounds balanced.',
  'It usually works because it respects their time while still moving things forward.',
  'I always overthink email tone.',
  'Most people do. Simple language is usually the safest choice.',
  'I have been trying to exercise more consistently.',
  'What is getting in the way right now?',
  'Mostly energy. After work I feel like I am already done for the day.',
  'Then try moving some workouts earlier or making them shorter on weekdays.',
  'Shorter workouts still count, right?',
  'Absolutely. Consistency matters more than perfect duration.',
  'I think I keep treating exercise like it only matters if it is intense.',
  'That mindset makes it much harder to build momentum.',
  'So the goal is to make the habit easier to repeat.',
  'Yes. Repetition builds the floor that ambition can stand on later.',
  'I need to make a decision, but neither option feels clearly right.',
  'When that happens, compare the regrets instead of the features.',
  'Regrets?',
  'Ask which choice you would be more disappointed not to try.',
  'That is interesting. It changes the question.',
  'Sometimes a better question unlocks the answer faster than more analysis.',
  'I have been feeling stuck creatively.',
  'Are you trying to make something good before you let yourself make something rough?',
  'Honestly, yes.',
  'Then your first job is volume, not polish.',
  'So lower the quality bar on purpose for a while?',
  'Exactly. Momentum often returns once the fear of a weak first draft goes away.',
  'That is uncomfortable, but probably true.',
  'Creative progress is often messy before it looks impressive.',
  'Do you have a favorite way to reset after a stressful day?',
  'Usually a walk, a shower, and something predictable to eat.',
  'Nothing fancy?',
  'Not usually. The point is to signal safety, not excitement.',
  'I like that idea.',
  'Simple routines work because they do not ask much from you when your energy is low.',
  'I want to get better at asking questions in conversations.',
  'Ask about specifics instead of asking huge open-ended questions every time.',
  'Can you give me an example?',
  'Instead of asking how work is, ask what part of the day felt easiest or hardest.',
  'That would probably lead to better answers.',
  'It usually does because people can picture a concrete moment.',
  'I have too many tabs open in my head and in my browser.',
  'Then pick one place to reduce noise first, physical or digital, and finish that small reset.',
  'Why only one place?',
  'Because finishing one cleanup is more calming than half-finishing three of them.',
  'That is annoyingly accurate.',
  'It is also why small wins change your mood faster than vague intentions.',
  'I am trying to learn something technical, but I keep bouncing between topics.',
  'Pick one project that forces the concepts to connect.',
  'So not just more tutorials?',
  'Right. Tutorials explain pieces, but projects reveal what you actually understand.',
  'That probably explains why I forget things so quickly.',
  'Knowledge sticks better when it solves a real problem in front of you.',
];
