/*
 * All path, URL, and prefix constants for the copy-examples boundary.
 *
 * Centralising them here keeps the sub-modules free of string literals and
 * makes global find-and-replace trivial when paths change.
 */

import path from 'node:path';

/** Console prefix prepended to every log line emitted by this boundary. */
export const DOCS_EXAMPLES_LOG_PREFIX = '[docs:examples]';

/** Absolute path to the `docs/examples/` directory that receives all published example pages and the landing page. */
export const DOCS_EXAMPLES_DIR = path.resolve('docs', 'examples');

/** Shared filename used for both the source example entrypoints and the published docs page copies. */
export const EXAMPLE_ENTRY_FILE_NAME = 'index.html';

/**
 * Relative path to the shared docs theme stylesheet as seen from the
 * `docs/examples/` landing-page level.
 */
export const DOCS_THEME_STYLESHEET_PATH = '../assets/theme.css';

/**
 * Relative path to the shared docs theme stylesheet as seen from inside a
 * source example folder (`examples/<name>/`).
 *
 * This is the value that appears in source `index.html` files and must be
 * rewritten to {@link EXAMPLE_PAGE_THEME_STYLESHEET_PATH} when copying into docs.
 */
export const REPO_EXAMPLE_THEME_STYLESHEET_PATH = '../../docs/assets/theme.css';

/**
 * Relative path to the tooltip runtime as seen from inside a source example
 * folder (`examples/<name>/`).
 *
 * This is the value that appears in source `index.html` files and must be
 * rewritten to {@link EXAMPLE_PAGE_TOOLTIP_RUNTIME_PATH} when copying into docs.
 */
export const REPO_EXAMPLE_TOOLTIP_RUNTIME_PATH =
  '../../docs/assets/theme-tooltips.js';

/**
 * Relative path back to the docs home (`docs/index.html`) as seen from the
 * `docs/examples/` landing-page level.
 */
export const DOCS_HOME_PATH = '../index.html';

/**
 * Relative path to the examples landing page itself, used as the `active`
 * nav link on the landing page.
 */
export const EXAMPLES_HOME_PATH = './index.html';

/**
 * Relative path to the shared docs theme stylesheet as seen from inside a
 * published example page (`docs/examples/<name>/`).
 */
export const EXAMPLE_PAGE_THEME_STYLESHEET_PATH = '../../assets/theme.css';

/**
 * Relative path to the tooltip runtime as seen from inside a published example
 * page (`docs/examples/<name>/`).
 */
export const EXAMPLE_PAGE_TOOLTIP_RUNTIME_PATH =
  '../../assets/theme-tooltips.js';

/**
 * Relative path back to the docs home as seen from inside a published example
 * page (`docs/examples/<name>/`).
 */
export const EXAMPLE_PAGE_DOCS_HOME_PATH = '../../index.html';

/**
 * Relative path back to the examples landing page as seen from inside a
 * published example page (`docs/examples/<name>/`).
 */
export const EXAMPLE_PAGE_EXAMPLES_HOME_PATH = '../index.html';

/** Base GitHub repository URL used to construct all source-file and branch-tree links in published pages. */
export const GITHUB_REPOSITORY_URL = 'https://github.com/reicek/NeatapticTS';

/** URL prefix for source file links pointing at the main branch tree. */
export const GITHUB_MAIN_BRANCH_URL = `${GITHUB_REPOSITORY_URL}/tree/main`;

/**
 * Opening token of the generated-file warning comment prepended to every
 * published example page.
 *
 * The script checks for this prefix before prepending to avoid double-stamping
 * pages that are re-processed in the same run.
 */
export const GENERATED_EXAMPLE_PAGE_COMMENT_PREFIX =
  '<!-- Generated by scripts/copy-examples.ts.';
