name: Manual release pipeline

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Version bump level (patch, minor, major)'
        required: true
        default: 'patch'
      branch:
        description: 'Branch to release from'
        required: true
        default: 'develop'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump version, create tag and push
        run: |
          npm version ${{ github.event.inputs.level }} -m "chore(release): %s [ci skip]"
          git push origin HEAD --follow-tags
      - name: Done
        run: echo "Version bumped and tags pushed. The release workflows will run on tag/release publish."

  publish:
    needs: release
    uses: ./.github/workflows/publish.yml
    with:
      run_publish: 'true'
      release_tag: ${{ github.ref }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
